---
title: "Simple document"
output: html_document
---


```{r, echo=FALSE, message=FALSE}
library(tidyverse)
library(janitor)
library(readxl)
library(haven)
```
## Import some data

l want to import `FAS_litters.csv`,

```{r}
litters_df <- read.csv("data/FAS_litters.csv")
```

Yay! l want better names.

``` {r}
names(litters_df)
litters_df <- janitor::clean_names(litters_df)
```

```{r,eval=FALSE}
views(litters_df)
```

```{r}
skimr::skim(litters_df)
```

## Arguments in `read_csv`

```{r}
litters_df1 <- 
  read_csv(
    "data/FAS_litters.csv",
    skip = 5,
    col_names = FALSE ,
    na  = "Low8")
```
## Reading from Excel

Reading MLB data
```{r}
mlb11_df <- read_excel("data/mlb11.xlsx")
```
LotR words is next
```{r}
fellow_df <- read_excel("data/LotR_Words.xlsx",range="B3:D6")
```

##Read a SAS file
```{r}
pulse_df <- read_sas("data/public_pulse_data.sas7bdat",encoding="latin1")
```

why note use read.csv

`read.csv` doesn't give `tibble` and that's really bad
```{r,eval=FALSE}
litters_df2 <- read.csv("data/FAS_litters.csv")
litters_df2 <- janitor::clean_names(litters_df2)

pups_df <- read.csv("data/FAS_pups.csv")
pups_df <- janitor::clean_names(pups_df)
```

## how do l export data

there's a good way!
```{r}
write_csv(fellow_df,"data/fellowship_words.csv")
```

## 'select'

Let's slect some columns

```{r}
select(litters_df2,group,litter_number)
##Choose the beginning columns
select(litters_df2,group,starts_with("pups"))
## you can use - to get rid of some columns
select(litters_df2,-litter_number)
## use GROUP to substitute group, and choose them
select(litters_df2,GROUP = group)
## rename to rename and only rename
rename(litters_df2,GROUP = group)
## relocate
relocate(litters_df2,)
```

## filter
let's get rid of rows
```{r}
filter(litters_df2,gd_of_birth == 20)
filter(litters_df2,group == "Con7")
filter(litters_df2,gd0_weight < 23)
##use ! for something that is not
filter(litters_df2,pups_survive !=4)
filter(litters_df2,!(group == "Con7"))
## use %in% set condition
filter(litters_df2,group %in% c("Con7","Con8"))
## use | for meeting only one condition
filter(litters_df2,group == "Con7"| gd_of_birth ==20)
##get rid of na
drop_na

```


